### ISSUE TITLE
Epic 1 : Develop - Implement UserList Component

### ISSUE THREAD

**Issue by suhasss077** [BitBytes-team/Project-5-8#1]
As a developer, I want the assignee to create the UserList component, which will be embedded in the sidebar of our Photo Sharing Application. This component should provide a list of user names. When a user name is clicked, the content view area should switch to display the details of the selected user.

**Comment by ruchitha007** [comment]
// import React from 'react';
// import {
//   Divider,
//   List,
//   ListItem,
//   ListItemText,
//   Typography,Link,Button
// }
// from '@mui/material';
// import './userList.css';

// /**
//  * Define UserList, a React component of project #5
//  */
// class UserList extends React.Component {
//   constructor(props) {
//     super(props);
//     this.state = {
//       users: window.models.userListModel(),
//           };
    
//   }
//   handleUserClick = (user) => {
//     this.props.setTopName(`${user.first_name} ${user.last_name}`);
    
//   };
//   render() {
    
//     return ( 
      
//       <div>
        
//         <List component="nav">
//   {this.state.users.map((user) => (
//     <div key={user._id}>
//       <ListItem>
//         <Button
//           component={Link}
//           to={`/users/${user._id}`}
//           className="ButtonStyle"
//           onClick={() => {
//             this.handleUserClick(user);
//             console.log(user);
//           }}
//         >
//           {`${user.first_name} ${user.last_name}`}
//         </Button>
//       </ListItem>
//       <Divider />
//     </div>
//   ))}
//         </List>

//         <Typography variant="body1">
//           The model comes in from window.models.userListModel()
//         </Typography>
//       </div>
//     );
//   }
// }

// export default UserList;
// import React from 'react';
// import { Divider, List, ListItem, Button} from '@mui/material';
// import { Link } from 'react-router-dom';  // Import Link from react-router-dom
// import './userList.css';
// // import FetchModel from '../../lib/fetchModelData';

// class UserList extends React.Component {
//   constructor(props) {
//     super(props);
//     this.state = {
//       userList: [],
//     };
//   }

//   componentDidMount() {
//     const userList = window.models.userListModel();
//     this.setState({ userList });
//   }

//   handleUserClick = (user) => {
//          this.props.setTopName(`User Details of ${user.first_name} ${user.last_name}`);
        
//        };
//   render() {
//     const { userList } = this.state;

//     return (
//       <div >
//         <div>
//           <List component="nav">
//             {userList.map((user) => (
//               <div key={user._id}>
//                 <ListItem>
//                   <Button
//                   onClick={() => {
//                     this.handleUserClick(user); 
//                 }}
//                     component={Link}
//                     to={`/users/${user._id}`}
//                     className="ButtonStyle" 
//                   >
//                     {`${user.first_name} ${user.last_name}`}
//                   </Button>
//                 </ListItem>
//                 <Divider />
//               </div>
//             ))}
//           </List>
//         </div>
//         <div style={{ width: '70%' }}>
//           {this.props.children}
//         </div>
//       </div>
//     );
//   }
// }
// export default UserList;
import React from 'react';
import { Divider, List, ListItem, Button } from '@mui/material';
import { Link } from 'react-router-dom';
import FetchModel from '../../lib/fetchModelData';
import './userList.css';

class UserList extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      userList: [],
    };
  }

  componentDidMount() {
    const url = '/user/list';

    FetchModel(url)
      .then((response) => {
        this.setState({ userList: response.data });
      })
      .catch((error) => {
        console.error('Error fetching user list:', error);
      });
  }

  handleUserClick = (user) => {
    this.props.setTopName(`User Details of ${user.first_name} ${user.last_name}`);

  };
render() {
const { userList } = this.state;

return (
 <div >
   <div>
     <List component="nav">
       {userList.map((user) => (
         <div key={user._id}>
           <ListItem>
             <Button
             onClick={() => {
               this.handleUserClick(user); 
           }}
               component={Link}
               to={`/users/${user._id}`}
               className="ButtonStyle" 
             >
               {`${user.first_name} ${user.last_name}`}
             </Button>
           </ListItem>
           <Divider />
         </div>
       ))}
     </List>
   </div>
   <div style={{ width: '70%' }}>
     {this.props.children}
   </div>
 </div>
);
}
}
export default UserList;
  


// // import React from 'react';
// // import { Typography, Button, Grid } from '@mui/material';
// // import { Link } from 'react-router-dom';
// // import './userDetail.css';

// // class UserDetail extends React.Component {
// //   constructor(props) {
// //     super(props);
// //     this.state = {
// //       user: null
// //     };
// //   }

// //   componentDidMount() {
// //     this.fetchUserDetails();
// //   }

// //   componentDidUpdate(prevProps) {
// //     const { match } = this.props;
// //     const { userId } = match.params;

// //     if (prevProps.match.params.userId !== userId || !this.state.user ) {
// //       this.fetchUserDetails();
// //       console.log(userId);
// //     }
// //   }

// //   fetchUserDetails() {
// //     const { match } = this.props;
// //     const { userId } = match.params;
  
// //     try {
// //       const user = window.models.userModel(userId);
// //       this.setState({ user });
// //     } catch (error) {
// //       console.error('Error fetching user details:', error);
// //     }
// //   }
  

// //   render() {
// //     const { user } = this.state;

// //     return (
// //       <div>
// //         {user ? ( 
//           // <div>
//           // <Grid container justifyContent="space-between">
//           //   <Grid item>
//           //     <Button component={Link} to={`/photos/${user._id}`} variant="contained" color="primary" onClick={()=> {console.log(user._id);}}>
//           //       User Photos
//           //     </Button>
//           //   </Grid>
//           // </Grid>
        
//           // <div className="user-detail-box" style={{ marginTop: '16px', border: '1px solid #e74c3c', padding: '8px', borderRadius: '5px', backgroundColor: '#f5f5f5', boxShadow: '0 0 10px rgba(231, 76, 60, 0.7)', transition: 'box-shadow 0.3s' }}>
//           //   <p style={{ fontWeight: 'bold', fontSize: '1em' }}>
//           //     First Name
//           //   </p>
//           //   <p style={{ fontSize: '0.9em', color: '#333' }}>
//           //     {user.first_name}
//           //   </p>
//           // </div>
          
//           // {/* Include other user details here */}
          
//           // <div className="user-detail-box" style={{ border: '1px solid #e74c3c', padding: '8px', borderRadius: '5px', marginTop: '10px', backgroundColor: '#f5f5f5', boxShadow: '0 0 10px rgba(231, 76, 60, 0.7)', transition: 'box-shadow 0.3s' }}>
//           //   <p style={{ fontWeight: 'bold', fontSize: '1em' }}>
//           //     Last Name
//           //   </p>
//           //   <p style={{ fontSize: '0.9em', color: '#333' }}>
//           //     {user.last_name}
//           //   </p>
//           // </div>
//           // <div className="user-detail-box" style={{ border: '1px solid #e74c3c', padding: '8px', borderRadius: '5px', marginTop: '10px', backgroundColor: '#f5f5f5', boxShadow: '0 0 10px rgba(231, 76, 60, 0.7)', transition: 'box-shadow 0.3s' }}>
//           //   <p style={{ fontWeight: 'bold', fontSize: '1em' }}>
//           //     Location
//           //   </p>
//           //   <p style={{ fontSize: '0.9em', color: '#333' }}>
//           //     {user.location}
//           //   </p>
//           // </div>
//           // <div className="user-detail-box" style={{ border: '1px solid #e74c3c', padding: '8px', borderRadius: '5px', marginTop: '10px', backgroundColor: '#f5f5f5', boxShadow: '0 0 10px rgba(231, 76, 60, 0.7)', transition: 'box-shadow 0.3s' }}>
//           //   <p style={{ fontWeight: 'bold', fontSize: '1em' }}>
//           //     Description
//           //   </p>
//           //   <p style={{ fontSize: '0.9em', color: '#333' }}>
//           //     {user.description}
//           //   </p>
//           // </div>
//           // <div className="user-detail-box" style={{ border: '1px solid #e74c3c', padding: '8px', borderRadius: '5px', marginTop: '10px', backgroundColor: '#f5f5f5', boxShadow: '0 0 10px rgba(231, 76, 60, 0.7)', transition: 'box-shadow 0.3s' }}>
//           //   <p style={{ fontWeight: 'bold', fontSize: '1em' }}>
//           //     Occupation
//           //   </p>
//           //   <p style={{ fontSize: '0.9em', color: '#333' }}>
//           //     {user.occupation}
//           //   </p>
//           // </div>
//           // </div>
        
        
        
// //         ) : (
// //           <Typography variant="body1" className="user-detail-box loading-text">
// //             Loading user details...
// //           </Typography>
// //         )}
// //       </div>
// //     );
// //   }
// // }

// // export default UserDetail;

// import React from 'react';
// import { Typography, Button, Grid } from '@mui/material';
// import { Link } from 'react-router-dom';
// import './userDetail.css';
// import FetchModel from '../../lib/fetchModelData';

// class UserDetail extends React.Component {
//   constructor(props) {
//     super(props);
//     this.state = {
//       user: null,
//     };
//   }

//   componentDidMount() {
//     this.fetchUserDetails();
//   }

//   componentDidUpdate(prevProps) {
//     const { match } = this.props;
//     const { userId } = match.params;

//     if (prevProps.match.params.userId !== userId || !this.state.user) {
//       this.fetchUserDetails(userId);
//     }
//   }

//   fetchUserDetails(userId) {
//     const { match } = this.props;

//     FetchModel(`/user/${userId}`)
//       .then((response) => {
//         this.setState({ user: response.data });
//       })
//       .catch((error) => {
//         console.error('Error fetching user details:', error);
//       });
//   }

//   render() {
//     const { user } = this.state;

//     return (
//       <div>
//         {user ? (
//           <div>
//           <Grid container justifyContent="space-between">
//             <Grid item>
//               <Button component={Link} to={`/photos/${user._id}`} variant="contained" color="primary" onClick={()=> {console.log(user._id);}}>
//                 User Photos
//               </Button>
//             </Grid>
//           </Grid>
        
//           <div className="user-detail-box" style={{ marginTop: '16px', border: '1px solid #e74c3c', padding: '8px', borderRadius: '5px', backgroundColor: '#f5f5f5', boxShadow: '0 0 10px rgba(231, 76, 60, 0.7)', transition: 'box-shadow 0.3s' }}>
//             <p style={{ fontWeight: 'bold', fontSize: '1em' }}>
//               First Name
//             </p>
//             <p style={{ fontSize: '0.9em', color: '#333' }}>
//               {user.first_name}
//             </p>
//           </div>
          
//           {/* Include other user details here */}
          
          // <div className="user-detail-box" style={{ border: '1px solid #e74c3c', padding: '8px', borderRadius: '5px', marginTop: '10px', backgroundColor: '#f5f5f5', boxShadow: '0 0 10px rgba(231, 76, 60, 0.7)', transition: 'box-shadow 0.3s' }}>
          //   <p style={{ fontWeight: 'bold', fontSize: '1em' }}>
          //     Last Name
          //   </p>
          //   <p style={{ fontSize: '0.9em', color: '#333' }}>
          //     {user.last_name}
          //   </p>
          // </div>
          // <div className="user-detail-box" style={{ border: '1px solid #e74c3c', padding: '8px', borderRadius: '5px', marginTop: '10px', backgroundColor: '#f5f5f5', boxShadow: '0 0 10px rgba(231, 76, 60, 0.7)', transition: 'box-shadow 0.3s' }}>
          //   <p style={{ fontWeight: 'bold', fontSize: '1em' }}>
          //     Location
          //   </p>
          //   <p style={{ fontSize: '0.9em', color: '#333' }}>
          //     {user.location}
          //   </p>
          // </div>
          // <div className="user-detail-box" style={{ border: '1px solid #e74c3c', padding: '8px', borderRadius: '5px', marginTop: '10px', backgroundColor: '#f5f5f5', boxShadow: '0 0 10px rgba(231, 76, 60, 0.7)', transition: 'box-shadow 0.3s' }}>
          //   <p style={{ fontWeight: 'bold', fontSize: '1em' }}>
          //     Description
          //   </p>
          //   <p style={{ fontSize: '0.9em', color: '#333' }}>
          //     {user.description}
          //   </p>
          // </div>
          // <div className="user-detail-box" style={{ border: '1px solid #e74c3c', padding: '8px', borderRadius: '5px', marginTop: '10px', backgroundColor: '#f5f5f5', boxShadow: '0 0 10px rgba(231, 76, 60, 0.7)', transition: 'box-shadow 0.3s' }}>
          //   <p style={{ fontWeight: 'bold', fontSize: '1em' }}>
          //     Occupation
          //   </p>
          //   <p style={{ fontSize: '0.9em', color: '#333' }}>
          //     {user.occupation}
          //   </p>
          // </div>
          // </div>
//         ) : (
//           <Typography variant="body1" className="user-detail-box loading-text">
//             Loading user details...
//           </Typography>
//         )}
//       </div>
//     );
//   }
// }

// export default UserDetail;

import React from 'react';
import { Typography, Button, Grid } from '@mui/material';
import { Link } from 'react-router-dom';
import './userDetail.css';
import  FetchModel  from '../../lib/fetchModelData'; // Import the FetchModel function

class UserDetail extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      user: null,
    };
  }

  componentDidMount() {
    this.fetchUserDetails();
  }

  componentDidUpdate(prevProps) {
    const { match } = this.props;
    const { userId } = match.params;

    if (prevProps.match.params.userId !== userId || !this.state.user) {
      this.fetchUserDetails();
    }
  }

  fetchUserDetails() {
    const { match } = this.props;
    const { userId } = match.params;

    // Define the URL to fetch the user data
    const url = `/user/${userId}`;

    FetchModel(url) // Use the FetchModel function
      .then((response) => {
        this.setState({ user: response.data });
      })
      .catch((error) => {
        console.error('Error fetching user details:', error);
      });
  }

  render() {
    const { user } = this.state;

    return (
      <div>
        {user ? (
          <div>
            <Grid container justifyContent="space-between">
              <Grid item>
                <Button
                  component={Link}
                  to={`/photos/${user._id}`}
                  variant="contained"
                  color="primary"
                >
                  User Photos
                </Button>
              </Grid>
            </Grid>

            <div
              className="user-detail-box"
              style={{
                marginTop: '16px',
                border: '1px solid #e74c3c',
                padding: '8px',
                borderRadius: '5px',
                backgroundColor: '#f5f5f5',
                boxShadow: '0 0 10px rgba(231, 76, 60, 0.7)',
                transition: 'box-shadow 0.3s',
              }}
            >
              <p style={{ fontWeight: 'bold', fontSize: '1em' }}>First Name</p>
              <p style={{ fontSize: '0.9em', color: '#333' }}>{user.first_name}</p>
            </div>

            <div className="user-detail-box" style={{ border: '1px solid #e74c3c', padding: '8px', borderRadius: '5px', marginTop: '10px', backgroundColor: '#f5f5f5', boxShadow: '0 0 10px rgba(231, 76, 60, 0.7)', transition: 'box-shadow 0.3s' }}>
            <p style={{ fontWeight: 'bold', fontSize: '1em' }}>
              Last Name
            </p>
            <p style={{ fontSize: '0.9em', color: '#333' }}>
              {user.last_name}
            </p>
            </div>
          <div className="user-detail-box" style={{ border: '1px solid #e74c3c', padding: '8px', borderRadius: '5px', marginTop: '10px', backgroundColor: '#f5f5f5', boxShadow: '0 0 10px rgba(231, 76, 60, 0.7)', transition: 'box-shadow 0.3s' }}>
            <p style={{ fontWeight: 'bold', fontSize: '1em' }}>
              Location
            </p>
            <p style={{ fontSize: '0.9em', color: '#333' }}>
              {user.location}
            </p>
          </div>
          <div className="user-detail-box" style={{ border: '1px solid #e74c3c', padding: '8px', borderRadius: '5px', marginTop: '10px', backgroundColor: '#f5f5f5', boxShadow: '0 0 10px rgba(231, 76, 60, 0.7)', transition: 'box-shadow 0.3s' }}>
            <p style={{ fontWeight: 'bold', fontSize: '1em' }}>
              Description
            </p>
            <p style={{ fontSize: '0.9em', color: '#333' }}>
              {user.description}
            </p>
          </div>
          <div className="user-detail-box" style={{ border: '1px solid #e74c3c', padding: '8px', borderRadius: '5px', marginTop: '10px', backgroundColor: '#f5f5f5', boxShadow: '0 0 10px rgba(231, 76, 60, 0.7)', transition: 'box-shadow 0.3s' }}>
            <p style={{ fontWeight: 'bold', fontSize: '1em' }}>
              Occupation
            </p>
            <p style={{ fontSize: '0.9em', color: '#333' }}>
              {user.occupation}
            </p>
          </div>
          </div>
        ) : (
          <Typography variant="body1" className="user-detail-box loading-text">
            Loading user details...
          </Typography>
        )}
      </div>
    );
  }
}

export default UserDetail;


Acceptance Criteria: 

The UserList component is successfully implemented and functional within the sidebar of the application. 

The UserList component fetches the list of users from the model data and dynamically displays user names. 

When a user name in the list is clicked, the content view area updates to display the details of the selected user. 

The user details are accurate, and the transition between user names and user details is smooth and responsive.
