### ISSUE TITLE
Epic 2 : Develop - Implement FetchModel Function

### ISSUE THREAD

**Issue by Sharu201101** [BitBytes-team/Project-5-8#4]
As a developer, I want the assignee to implement the FetchModel function within the lib/fetchModelData.js file. This function should be responsible for fetching model data from the web server using XMLHttpRequest. It must be capable of handling multiple outstanding requests simultaneously and returning the response as a parsed JSON object.

**Comment by Jahnavi-0305** [comment]
Acceptence criteria:
The FetchModel function is successfully implemented within the lib/fetchModelData.js file. 

The function can handle multiple concurrent requests, ensuring the application's responsiveness. 

The FetchModel function accurately retrieves and parses model data from the web server and returns it as a JSON object within a Promise. 

Error handling is in place, and the Promise is rejected with an object containing status and statusText properties when an error occurs.

CODE: 

// eslint-disable-next-line import/no-unresolved
var Promise = require("Promise");
function FetchModel(url) {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open('GET', url, true);

    xhr.onload = () => {
      if (xhr.status >= 200 && xhr.status < 300) {
        try {
          const response = JSON.parse(xhr.responseText);
          resolve({ data: response });
        } catch (error) {
          // eslint-disable-next-line prefer-promise-reject-errors
          reject({
            status: xhr.status,
            statusText: 'Error parsing response as JSON',
          });
        }
      } else {
        // eslint-disable-next-line prefer-promise-reject-errors
        reject({
          status: xhr.status,
          statusText: xhr.statusText,
        });
      }
    };

    xhr.onerror = () => {
      // eslint-disable-next-line prefer-promise-reject-errors
      reject({
        status: xhr.status,
        statusText: xhr.statusText,
      });
    };

    xhr.send();
  });
}

export default FetchModel;
