### ISSUE TITLE
Epic 2 : Testing : Validate FetchModel and Component Integration

### ISSUE THREAD

**Issue by Sharu201101** [BitBytes-team/Project-5-8#5]
As a developer , I want the assignee to test the FetchModel function to ensure it successfully fetches model data from the web server. Additionally, test the integration of the FetchModel function with the UserDetail, UserList, and UserPhotos components to verify that the application functions correctly. 

Test Criteria : 

- Test the FetchModel function with various URLs to fetch data and validate the responses. 

- Ensure that FetchModel handles errors and rejected promises appropriately. 

- Verify that the UserDetail, UserList, and UserPhotos components correctly use the FetchModel function to fetch data from the server. 

- Confirm that the application still displays the version number in the TopBar component as expected when visiting http://localhost:3000/photo-share.html.

**Comment by KpSai96** [comment]
The FetchModel function successfully fetches data from the web server, and all test cases pass. 

Errors are handled correctly by FetchModel, and rejected promises contain necessary information. 

The UserDetail, UserList, and UserPhotos components integrate seamlessly with FetchModel, and the application functions as expected. 

The version number is displayed in the TopBar component when accessing http://localhost:3000/photo-share.html, indicating the FetchModel and component integration is working.
