### ISSUE TITLE
Epic 2 : Code Review : Review and Refactor Component Code

### ISSUE THREAD

**Issue by Sharu201101** [BitBytes-team/Project-5-8#6]
As a developer, the assignee’s goal is to conduct a comprehensive code review of the component code within UserDetail.jsx, UserList.jsx, and UserPhotos.jsx. The primary focus is to ensure that these components no longer access model data through the window.models object. Instead, they should use the newly implemented FetchModel function to request data from the server. This review will also assess the refactored code for adherence to best practices. 

Review Criteria : 

- Review the code in UserDetail.jsx, UserList.jsx, and UserPhotos.jsx to verify that these components have been updated to use the FetchModel function for data retrieval. 

- Ensure that there are no accesses to the window.models object within the component code. 

- Assess the refactored code for clarity, readability, and adherence to coding standards and best practices. 

- Identify and address any issues, discrepancies, or areas for improvement found during the code review.

**Comment by BhavagnaT** [comment]
Reviewed and verified the components in the respected files haven been updated to use the FetchModel for data retievel. 
Made sure that there is no accesses to the window.models object 
The refactored code adheres to coding standards and best practices, ensuring it is clean, maintainable, and well-structured.
