### ISSUE TITLE
Code Review - Database Integration

### ISSUE THREAD

**Issue by ruchitha007** [BitBytes-team/Project-5-8#8]
As a developer, I want the assignee to review the code changes for database integration to ensure they meet project requirements and coding standards. 

Review Criteria :  

Review webServer.js to confirm the successful removal of magic models and the usage of MongoDB models. 

Evaluate the MongoDB schemas and models to ensure they accurately represent the application's data structures. 

Review the implementation of API routes ('/test', '/user/list', '/user/:id', and '/photosOfUser/:id') to verify that they adhere to the specified requirements. 

Confirm that object cloning through JSON serialization has been correctly implemented to handle MongoDB models.

**Comment by Jahnavi-0305** [comment]
- I've reviewed the code changes, and everything looks good.  

- The magic models have been successfully replaced, and the API routes are implemented correctly.  

- The use of JSON serialization for object cloning is a suitable solution. Ready for testing.
